INSERT INTO GENEROS(NOMBRE) VALUES('Acción');
INSERT INTO GENEROS(NOMBRE) VALUES('Aventura');
INSERT INTO GENEROS(NOMBRE) VALUES('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES('Suspenso');
INSERT INTO GENEROS(NOMBRE) VALUES('Ciencia ficción');
INSERT INTO GENEROS(NOMBRE) VALUES('Fantasía');
INSERT INTO GENEROS(NOMBRE) VALUES('Romance');
INSERT INTO GENEROS(NOMBRE) VALUES('Animación');
INSERT INTO GENEROS(NOMBRE) VALUES('Crimen');
INSERT INTO GENEROS(NOMBRE) VALUES('Misterio');
INSERT INTO GENEROS(NOMBRE) VALUES('Terror');
INSERT INTO GENEROS(NOMBRE) VALUES('Documental');
INSERT INTO GENEROS(NOMBRE) VALUES('Histórico');
INSERT INTO GENEROS(NOMBRE) VALUES('Musical');

INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Chris Pratt', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Chris_Pratt_2018.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Scarlett Johansson', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Scarlett_Johansson_by_Gage_Skidmore_2_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Robert Downey Jr.', 'https://upload.wikimedia.org/wikipedia/commons/9/94/Robert_Downey_Jr_2014_Comic_Con_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Tom Hanks', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Tom_Hanks_2016.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Jennifer Lawrence', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Jennifer_Lawrence_SDCC_2015_X-Men.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Leonardo DiCaprio', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_Dicaprio_Cannes_2019.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Gal Gadot', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Gal_Gadot_2018_cropped_retouched.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Dwayne Johnson', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Dwayne_Johnson_2014_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Emma Stone', 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Chris Hemsworth', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Angelina Jolie', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Angelina_Jolie_2_June_2014_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Will Smith', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/TechCrunch_Disrupt_2019_%2848834434641%29_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Natalie Portman', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Natalie_Portman_%2848470988352%29_%28cropped%29.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Tom Cruise', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Tom_Cruise_by_Gage_Skidmore_2.jpg');

INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 1', 1, '2023-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 2', 9, '2023-05-18');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 3', 5, '2023-03-07');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 4', 3, '2023-06-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 5', 11, '2023-02-14');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 6', 12, '2023-04-30');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 7', 7, '2023-01-22');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 8', 6, '2023-03-11');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 9', 2, '2023-06-09');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 10', 15, '2023-05-02');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 11', 8, '2023-04-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 12', 4, '2023-01-17');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 13', 10, '2023-02-28');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 14', 13, '2023-05-11');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 15', 8, '2023-06-12');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 16', 14, '2023-02-05');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 17', 3, '2023-03-29');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 18', 9, '2023-04-24');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 19', 5, '2023-01-05');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Película Prueba 20', 7, '2023-06-07');